package main

import (
	"github.com/mbdeguzman/xmas_party/models"
	"github.com/uadmin/uadmin"
)

func SampleData() {
	// * Load the initial data for the company
	company := []models.Company{}
	uadmin.All(&company)
	defaultCompany := []models.Company{
		{
			Name: "                        Altin Pawnshop",
		},
		{
			Name: "           IntegraNet Network Services",
		},
		{
			Name: "   IntegrityNet Solutions and Services",
		},
		{
			Name: "        LuksLofts Hotel and Residences",
		},
		{
			Name: "Share Cafe Restaurant and Event Center",
		},
		{
			Name: "               IntegrityNet Operations",
		},
	}

	if len(company) == 0 {
		for i := range defaultCompany {
			uadmin.Save(&defaultCompany[i])
		}
	}

	// TODO: Add the initial data for departments here

	// * Load the initial data for the employees
	employees := []models.Employees{}
	uadmin.All(&employees)
	defaultEmployees := []models.Employees{
		{
			EmployeeNumber:  "2076",
			Name:            "Aleta, Angelito",
			CompanyID:       uint(2),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "2221",
			Name:            "Amores, Jamico Jay",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2243",
			Name:            "Andal, Deus Mico",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2240",
			Name:            "Andal, Joan Marie",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2219",
			Name:            "Atienza, Raiza",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2220",
			Name:            "Babasa, Efren ",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2195",
			Name:            "Balmes, Neil Adrian",
			CompanyID:       uint(2),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "2186",
			Name:            "Blanco, K.Clyn ",
			CompanyID:       uint(2),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "2189",
			Name:            "Caniedo, Veronica ",
			CompanyID:       uint(2),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "2254",
			Name:            "Cantos, John Carlo ",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2232",
			Name:            "Castillo, Jem Wynona ",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2116",
			Name:            "Catapang, Angelica Mae ",
			CompanyID:       uint(2),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "2206",
			Name:            "Cena, Jan Joel ",
			CompanyID:       uint(2),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "2194",
			Name:            "Cerezo John Menard ",
			CompanyID:       uint(2),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "2235",
			Name:            "Cinco, Dennis ",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2250",
			Name:            "De Castro, Marck Junhel ",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2179",
			Name:            "De Guzman, Mark Bryan ",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2256",
			Name:            "Dela Cruz, Angelie ",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2260",
			Name:            "Dimayuga, Paul Vincent ",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2252",
			Name:            "Edulan, Marie Antoinnette ",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2241",
			Name:            "Enriquez, Revelyn ",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2242",
			Name:            "Escobio, D-Jay ",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2211",
			Name:            "Falo, David Alexis ",
			CompanyID:       uint(2),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "2233",
			Name:            "Frago, Nicole Anne ",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2231",
			Name:            "Garcia, Zeus  ",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2227",
			Name:            "Gupit, Alexander",
			CompanyID:       uint(2),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "2239",
			Name:            "Gutierrez, John Dariel",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2192",
			Name:            "Hebras, Sherlene",
			CompanyID:       uint(2),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "2257",
			Name:            "Lat, John Lemuel",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2200",
			Name:            "Lemita, Veejay Adolf",
			CompanyID:       uint(2),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "2210",
			Name:            "Loria, Jethro",
			CompanyID:       uint(2),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "2259",
			Name:            "Maalihan, Jayson",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2178",
			Name:            "Macaraig, Arvin Paulo",
			CompanyID:       uint(2),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "2245",
			Name:            "Magboo, Hsin Chin",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2177",
			Name:            "Magpantay, Joshua",
			CompanyID:       uint(2),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "2216",
			Name:            "Malibiran, Cristie",
			CompanyID:       uint(2),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "2184",
			Name:            "Malibiran, Mary Jane",
			CompanyID:       uint(2),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "2247",
			Name:            "Manzano, Mark Lester",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2263",
			Name:            "Mendoza, Dianne",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2253",
			Name:            "Mendoza Jr., Alejandro",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2236",
			Name:            "Montesa III, Francisco",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2213",
			Name:            "Ocampo, Marlon",
			CompanyID:       uint(2),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "2251",
			Name:            "Panganiban, Janne Nicole",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2255",
			Name:            "Payoyo, Rico",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2262",
			Name:            "Peñaflorida, Lenny",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2261",
			Name:            "Pentinio, Vanessa",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2176",
			Name:            "Reyes, Glecie Jane",
			CompanyID:       uint(2),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "2143",
			Name:            "Roco, Benjamin",
			CompanyID:       uint(2),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "2258",
			Name:            "Salazar, Alvin",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2144",
			Name:            "Taguba, Bryan",
			CompanyID:       uint(2),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "2264",
			Name:            "Ortega, Glen Ger Dawn",
			CompanyID:       uint(2),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "009845",
			Name:            "Abando, Kimberly Ann",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009671",
			Name:            "Agravio, Marjorie",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009022",
			Name:            "Alvarez, Cathlene Kate",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009787",
			Name:            "Amaro, Richwell",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009849",
			Name:            "Anoñuevo, Gil",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009606",
			Name:            "Antonio, Michelle",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009865",
			Name:            "Asciñas, Dannybel",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009554",
			Name:            "Atienza, Maria Jesusa",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009826",
			Name:            "Babao, Sarah Mae",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009863",
			Name:            "Balmes, Krishian Mae",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009890",
			Name:            "Biscocho, Madonna",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009096",
			Name:            "Bisula, Allan Anis",
			CompanyID:       uint(6),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "009140",
			Name:            "Boongaling, Marilou",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009231",
			Name:            "Borlaza, Anna Eaza Grace",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009057",
			Name:            "Briones, Jairus John",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009065",
			Name:            "Briones, Katherine",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009866",
			Name:            "Bulawan, Raquel",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009103",
			Name:            "Calubaquib, Carlo  Angelo ",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009674",
			Name:            "Cantos, Neriebel Marie",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009478",
			Name:            "Claus, Adela Paras",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009675",
			Name:            "Claus, Arlen Paras",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009852",
			Name:            "De Guzman, Marjorie Ann",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009753",
			Name:            "De Mesa, Joseph Allen",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009829",
			Name:            "Delos Reyes, Edannie",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009646",
			Name:            "Dimailig, Venice Angelica",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009099",
			Name:            "Dipasupil, Melanie",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009868",
			Name:            "Ebora, Daisyre",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009558",
			Name:            "Evangelista, Doralie",
			CompanyID:       uint(6),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "009756",
			Name:            "Gondra, Daniel",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009603",
			Name:            "Gunio, Glorilyn",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009236",
			Name:            "Hornilla, Baby Lene",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009832",
			Name:            "Lagran, Mark Anthony",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009363",
			Name:            "Landicho, Alvin Cris",
			CompanyID:       uint(6),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "009680",
			Name:            "Lazarte, Angelli",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009681",
			Name:            "Lim, Lara Elisse",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009855",
			Name:            "Macasinag, Eric",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009856",
			Name:            "Manalo, Mae Ericka Ivie",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009204",
			Name:            "Mandigma, Madonna",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009886",
			Name:            "Mandigma, Michael",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009684",
			Name:            "Mojica, Melissa",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009834",
			Name:            "Mondano, Arlene",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009686",
			Name:            "Morillo, Susan",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009604",
			Name:            "Napay, Marry Joy",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009858",
			Name:            "Norva, Katrina",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009056",
			Name:            "Oca, Joyce Anne Maginie",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009762",
			Name:            "Pal, Puja",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009309",
			Name:            "Perez, Anglebert",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009349",
			Name:            "Perez, Roylan",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009873",
			Name:            "Poliquit, Calvin ",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009869",
			Name:            "Quiñones, Anna Marie",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009837",
			Name:            "Rodolfo, Waynne",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009882",
			Name:            "Rosales, Jennifer Marielle",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009888",
			Name:            "Rosales, Nina Antonete",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009312",
			Name:            "Soliman, Percival",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009884",
			Name:            "Tapangco, Joana Lou",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009534",
			Name:            "Tayag, Maricar",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009872",
			Name:            "Tiquis, Maria Nicole",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009608",
			Name:            "Valebia, Lendy",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009901",
			Name:            "CATIENZA, MAILA",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009893",
			Name:            "ORTIZ, ELVIN ",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009895",
			Name:            "MEJIA, JUVY ANNE",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009903",
			Name:            "BALOTCOPO, KERVIN ",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009896",
			Name:            "MATIBAG, LORD IAN",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009899",
			Name:            "EJE, DAVID DANIEL ROGIE ",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009894",
			Name:            "MENDOZA, DANA MAY ",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009905",
			Name:            "MAGBUHAT, KRISTIAN ALLEN ",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009900",
			Name:            "DE GUZMAN, DENISE ",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009904",
			Name:            "ALCANTARA, MARIANNE ",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009902",
			Name:            "CANLUBO, JOHN JALLO ",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009892",
			Name:            "VALENCIA, MELODY",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009898",
			Name:            "MACATANGAY, MARIE JOY ",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009897",
			Name:            "MARAVE JR., DANILO",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009891",
			Name:            "VILLENA, GRACE ",
			CompanyID:       uint(6),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "21011",
			Name:            "Almario, Clarice",
			CompanyID:       uint(5),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "19121",
			Name:            "Ante, Eric",
			CompanyID:       uint(5),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009651",
			Name:            "Arcega, Percelet",
			CompanyID:       uint(5),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "22021",
			Name:            "Bernabe, Honeylet Farah",
			CompanyID:       uint(5),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "22030",
			Name:            "Castillo, Von Joshua",
			CompanyID:       uint(5),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "2238",
			Name:            "Catangay, Chyra Ann Anttonete",
			CompanyID:       uint(5),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "22001",
			Name:            "Claus, Angela Jhoy",
			CompanyID:       uint(5),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "20003",
			Name:            "Dalisay, Rolando",
			CompanyID:       uint(5),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "22009",
			Name:            "De Torres, Leopoldo Luis",
			CompanyID:       uint(5),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "19136",
			Name:            "Garcia, Kim Alven",
			CompanyID:       uint(5),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "22027",
			Name:            "Hermidilla, Nixon",
			CompanyID:       uint(5),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "009702",
			Name:            "Janer, Myrla",
			CompanyID:       uint(5),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "22013",
			Name:            "Lucero, Danica Marie",
			CompanyID:       uint(5),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "16087",
			Name:            "Maderazo, Aaron Paul",
			CompanyID:       uint(5),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "21007",
			Name:            "Moldon, Catherine",
			CompanyID:       uint(5),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "22017",
			Name:            "Padre, Reuel",
			CompanyID:       uint(5),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "19059",
			Name:            "Perez, Pocholo",
			CompanyID:       uint(5),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "15002",
			Name:            "Reyes, Alijah Alma",
			CompanyID:       uint(5),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "19002",
			Name:            "Samaniego, Evelyn",
			CompanyID:       uint(5),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "21001",
			Name:            "Serran, Richard",
			CompanyID:       uint(5),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "22016",
			Name:            "Tolentino, Jerry",
			CompanyID:       uint(5),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "19003",
			Name:            "Zafe, Rommel",
			CompanyID:       uint(5),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "16095",
			Name:            "Aday, Christian",
			CompanyID:       uint(4),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "19118",
			Name:            "Amboy, Eric William",
			CompanyID:       uint(4),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "22026",
			Name:            "Banaag, Jan Bernice",
			CompanyID:       uint(4),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "17005",
			Name:            "Cantos, Aprail",
			CompanyID:       uint(4),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "22029",
			Name:            "Cristobal, Ayla Faye",
			CompanyID:       uint(4),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "21012",
			Name:            "Delas Alas, Jay Mark",
			CompanyID:       uint(4),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "22003",
			Name:            "Delizo, Danica Pearl",
			CompanyID:       uint(4),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009193",
			Name:            "Lu, Szeerlon",
			CompanyID:       uint(4),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "22018",
			Name:            "Macalalad, Laiza",
			CompanyID:       uint(4),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "22008",
			Name:            "Marco, Kimberly Mae",
			CompanyID:       uint(4),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "22023",
			Name:            "Mariano, Alberto",
			CompanyID:       uint(4),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "009581",
			Name:            "Mendoza, Berwyn",
			CompanyID:       uint(4),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009441",
			Name:            "Pasay, Marino",
			CompanyID:       uint(4),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "22031",
			Name:            "Pila, Jiminette",
			CompanyID:       uint(4),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "19113",
			Name:            "Serrano, Arcenia",
			CompanyID:       uint(4),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "22012",
			Name:            "Silvestre, Rosette",
			CompanyID:       uint(4),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "17014",
			Name:            "Siman, Nestor",
			CompanyID:       uint(4),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009816",
			Name:            "Buan, John Louies",
			CompanyID:       uint(3),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009539",
			Name:            "Castillo, Gener",
			CompanyID:       uint(3),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009462",
			Name:            "Fabregas, Joebert",
			CompanyID:       uint(3),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009266",
			Name:            "Guiamoy, Juvienal",
			CompanyID:       uint(3),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009744",
			Name:            "Macatangay, Leodegario",
			CompanyID:       uint(3),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009006",
			Name:            "Macatangay, Richard Roy",
			CompanyID:       uint(3),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009501",
			Name:            "Manucal, Anthony",
			CompanyID:       uint(3),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009404",
			Name:            "Ongkiko, Karl Michael",
			CompanyID:       uint(3),
			RaffleQualified: false,
		},
		{
			EmployeeNumber:  "009288",
			Name:            "Roxas, Claro",
			CompanyID:       uint(3),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009811",
			Name:            "Santos, Nestor",
			CompanyID:       uint(3),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "009472",
			Name:            "Villadarez, Joel",
			CompanyID:       uint(3),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "000014",
			Name:            "Almodal, Jose Limuel",
			CompanyID:       uint(1),
			RaffleQualified: true,
		},
		{
			EmployeeNumber:  "000011",
			Name:            "Gayo, Dennis",
			CompanyID:       uint(1),
			RaffleQualified: true,
		},
	}

	if len(employees) == 0 {
		for i := range defaultEmployees {
			uadmin.Save(&defaultEmployees[i])
		}
	}
}
